# Generated by Django 5.2.15 on 2026-06-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('no_of_guest', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
